### PR TITLE
Stop leaking credentials warning

### LINKED ISSUE #57: Google Developer Warning
Hello,
I just received an email from google which reads as follows:

> Hello Google Play Developer,
> 
> We detected that your app(s) listed at the end of this email are potentially leaking credentials used to make network requests (HTTP and FTP).
> 
> Please check for cases where you use url-encoded basic access authentication, for example a URL such as https://username:password@www.example.com/. We recommend that you immediately change the credentials and redesign your app to avoid including them.
> 
> Next steps
> 
>     Sign in to your Developer Console and submit the updated version of your app.
>     Check back after five hours - we’ll show a warning message if the app hasn’t been updated correctly.
> 
> Exposed developer credentials can allow an attacker to compromise your systems which puts user data at risk. For other technical questions about the vulnerability, you can post to Stack Overflow and use the tag “android-security.”
> 
> We’re here to help
> 
> If you feel we have sent this warning in error, you can contact our developer support team.
> 
> Regards,
> 
> The Google Play Team

This email is for adding sentry in my project. I think that's the type of connection dsn.

Any idea or solution?
Thank you very much

### LINKED ISSUE #59: Add some Android device details by default to Events
Hi @joshdholtz,

I'm using code like this to build up a default set of device data to send along with crashes.

```Java
private static Map<String, String> readDeviceData(Context context) {
  final Map<String, String> deviceData = new HashMap<>();
  try {
    deviceData.put("Device", Build.DEVICE);
    deviceData.put("Brand", Build.BRAND);
    deviceData.put("Model", Build.MODEL);
    deviceData.put("Android Version", Build.VERSION.RELEASE);
    //deviceData.put("Android SDK", Build.VERSION.SDK); // Android 3
    deviceData.put("Android SDK", Integer.toString(Build.VERSION.SDK_INT)); // Android 4+
    deviceData.put("Manufacturer", Build.MANUFACTURER); // Android 4+

    // Read package information
    final String packageName = context.getPackageName();
    final PackageInfo packageInfo = context.getPackageManager().getPackageInfo(packageName, 0);
    deviceData.put("Package Name", packageName);
    deviceData.put("Package Version Name", packageInfo.versionName);
    deviceData.put("Package Version Code", Integer.toString(packageInfo.versionCode));

    // Read screen resolution in the format "800x600"
    // Normalised to have wider side first.
    final Object windowManager = context.getSystemService(Context.WINDOW_SERVICE);
    if (windowManager != null && windowManager instanceof WindowManager) {
        final DisplayMetrics metrics = new DisplayMetrics();
        ((WindowManager)windowManager).getDefaultDisplay().getMetrics(metrics);
        deviceData.put("ScreenResolution",
                        String.format("%sx%s",
                                Math.max(metrics.widthPixels, metrics.heightPixels),
                                Math.min(metrics.widthPixels, metrics.heightPixels)));
            }

    } catch (Exception e) {
      Log.d("Sentry", "Error reading device data", e);
    }
    return deviceData;
}
```

I use a `SentryEventCaptureListener` to add this `Map` to the `SentryEventBuilder` before capture.

I thought you might be able to add something like this to all events by default, or to create a function like

```Java
class Sentry {
   ... // snip

  public static SentryEventCaptureListener CreateDeviceDataCaptureListener() {
    final Map<String, String> deviceData = readDeviceData(context);
    return new Sentry.SentryEventCaptureListener() {
            @Override
            public Sentry.SentryEventBuilder beforeCapture(Sentry.SentryEventBuilder builder) {
                return builder.setExtra(deviceData);
            }
        }
  }
}
```

Data in Sentry:

sentry

### PR DESCRIPTION
**Pull request by joshdholtz**
Should fix #57 

I uploaded an APK with this version to Google Play and did not receive the error/warning that everyone was getting in #57

### CODE REVIEW

File: sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java [hunk 1]
```diff
@@ -102,6 +103,12 @@ private Sentry() {
 
 	}
 
+	private static void log(String text) {
+		if (debug) {
+			log(text);
```
Comment (cpowell001) [inline sentry-android/src/main/java/com/joshdholtz/sentry/Sentry.java]: If `debug = true`, `log` will just call itself recursively. Surely you mean `if(debug) { Log.d(text); }`
